
open cluster daemon (ocd) requires several libraries to be installed before stash can be built/executed.

These are:

 - libevent (2.0 or higher)

When the required libraries have been installed, build everything by doing

  make

and if successfull, install with

  sudo make install

